import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Center, Flex, Box, Input, Heading } from "@chakra-ui/react";
import useEnsData from "../hooks/useEns";
import Card from "../component/Card";
import { useState } from "react";
const Home: NextPage = () => {
  const [search, setSearch] = useState("");
  const { ensData } = useEnsData(undefined, search);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading mb={5}>{search}'s Ens Namecard</Heading>
        <ConnectButton />
        <Input my="5" onChange={(e) => setSearch(e.target.value)}></Input>
        <pre>{JSON.stringify(ensData, null, 2)}</pre>
        <Card cardData={ensData}></Card>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
